//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAddress()
        {
            this.tblManagers = new HashSet<tblManager>();
            this.tblPilots = new HashSet<tblPilot>();
            this.tblPlanes = new HashSet<tblPlane>();
        }

        public string AddressId { get; set; }
        [Required(ErrorMessage = "Please Enter HouseNo")]
        public string HouseNo { get; set; }
        [Required(ErrorMessage = "Please Enter AddressLine1")]
        public string AddressLine1 { get; set; }
        [Required(ErrorMessage = "Please Enter City")]
        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "please enter valid city name")]
        public string City { get; set; }
        [Required(ErrorMessage = "Please Enter State")]
        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "please enter valid state name")]
        public string State { get; set; }
        [Required(ErrorMessage = "Please Enter Country")]
        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "please enter valid country name")]
        public string Country { get; set; }
        [Required(ErrorMessage = "Please Enter PinNo")]
        [RegularExpression(@"^[1-9]{1}[0-9]{5}$", ErrorMessage = "please enter valid pin number")]
        public int PinNo { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblManager> tblManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPilot> tblPilots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlane> tblPlanes { get; set; }
    }
}
