//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblHanger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHanger()
        {
            this.tblPlaneAllocations = new HashSet<tblPlaneAllocation>();
        }
      
 
       
        public string Hanger_ID { get; set; }
        [Required(ErrorMessage = "Please Enter location of the hanger")]
        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "Invalid location name")]
        public string HangerLocation { get; set; }
        [Required(ErrorMessage = "Please enter capacity of hanger ")]

        
        public int HangerCapacity { get; set; }
        public string ManagerId { get; set; }
    
        public virtual tblManager tblManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlaneAllocation> tblPlaneAllocations { get; set; }
    }
}
