//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblManager()
        {
            this.tblHangers = new HashSet<tblHanger>();
        }
    
        public string ManagerId { get; set; }
        [Required(ErrorMessage = "Please Enter Manager Name")]
        public string ManagerName { get; set; }
        [Required(ErrorMessage = "Please Enter SSN")]
        public string SocialSecurityNo { get; set; }
        [Required(ErrorMessage = "Please Enter Date Of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime DateOfbirth { get; set; }
        [Required(ErrorMessage = "Please Select Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter Mobile Number")]
        [RegularExpression(@"^[7-9]{1}[0-9]{9}$", ErrorMessage = "Please Enter a valid Mobile number")]
        public string MobileNo { get; set; }
        [Required(ErrorMessage = "Please Enter Email")]
        [EmailAddress(ErrorMessage = "Please Enter a valid email")]
        public string EmailAddress { get; set; }
        public string AddressId { get; set; }


        public virtual tblAddress tblAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHanger> tblHangers { get; set; }
    }
}
