//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPlaneAllocation
    {
        public string PlaneID { get; set; }
        public string HangerID { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please select StartDate")]
        [CustomDateValidation(ErrorMessage = "Date must be greater today's date")]

        public System.DateTime StartDate { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please select EndDate")]
        [CustomDateValidation(ErrorMessage = "Date must be greater today's date")]
        public System.DateTime EndDate { get; set; }

        public virtual tblHanger tblHanger { get; set; }
        public virtual tblPlane tblPlane { get; set; }
    }
}
