//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPilot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPilot()
        {
            this.tblPlanes = new HashSet<tblPlane>();
        }
    
        public string Pilot_ID { get; set; }
        [Required(ErrorMessage = "Please Enter PilotName")]
        [RegularExpression(@"^[A-Za-z ]+$", ErrorMessage = "Invalid PilotName")]
        public string PilotName { get; set; }
        [Required(ErrorMessage = "Please Enter LicenseNo")]
        [RegularExpression(@"^[1-9]{1}[0-9]{9}$", ErrorMessage = "Invalid LicenseNo")]
        //[MaxLength(10, ErrorMessage = "10 digits only")]
        //[MinLength(10, ErrorMessage = "10 digits only")]
        public long LicenseNo { get; set; }
        [Required(ErrorMessage = "Please Enter SocialSecurityNo")]
        [RegularExpression(@"^[1-9]{1}[0-9]{9}$", ErrorMessage = "Please Enter valid social security number")]
        public string SocialSecurityNo { get; set; }
        [Required(ErrorMessage = "Please Enter DateofBirth")]
        [DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "Please Select Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter MobileNo")]
        [RegularExpression(@"^[7-9]{1}[0-9]{9}$", ErrorMessage = "Please Enter a valid Mobile number")]
        public string MobileNo { get; set; }
        [Required(ErrorMessage = "Please Enter EmailID")]
        [EmailAddress(ErrorMessage = "Please Enter a valid email")]

        public string EmailAddress { get; set; }        
        public string AddressId { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlane> tblPlanes { get; set; }
    }
}
